version: "3.3.1"
default_instance: "yarn"

# 共享配置
common:
  resourcemanager: "prod-resourcemanager"
  nodemanager: "prod-nodemanager"
  resourcemanager_port: 8088
  nodemanager_port: 8042
  timeout: 30
  verify_ssl: false
  use_https: true
  username: "autoevs"

# 多实例配置
instances:
  yarn:
    resourcemanager: "10.1.4.121"
    nodemanager: "prod-nodemanager"
    resourcemanager_port: 8090
    nodemanager_port: 8042
    timeout: 30
    verify_ssl: false
    use_https: true
    username: "autoevs"

  yarn1:
    resourcemanager: "prod-resourcemanager-1"
    nodemanager: "prod-nodemanager-1"
    resourcemanager_port: 8088
    nodemanager_port: 8042
    timeout: 30
    verify_ssl: false
    use_https: true
    username: "autoevs" 