# HBase配置
version: "2.4.17"
default_instance: "hbase"

# 共享配置
common:
  zookeeper_quorum: "zk1.example.com,zk2.example.com,zk3.example.com"
  zookeeper_port: 2181
  zookeeper_znode_parent: "/hbase"
  hbase_rootdir: "hdfs://hdfs.example.com:8020/hbase"
  hbase_tmp_dir: "/tmp/hbase"
  master_host: "hbase-master.example.com"
  master_port: 16000
  regionserver_host: "hbase-rs.example.com"
  regionserver_port: 16020
  timeout: 30

# 多实例配置
instances:
  hbase:
    zookeeper_quorum: "zk1.example.com,zk2.example.com,zk3.example.com"
    zookeeper_port: 2181
    zookeeper_znode_parent: "/hbase"
    hbase_rootdir: "hdfs://hdfs.example.com:8020/hbase"
    hbase_tmp_dir: "/tmp/hbase"
    master_host: "hbase-master.example.com"
    master_port: 16000
    regionserver_host: "hbase-rs.example.com"
    regionserver_port: 16020
    timeout: 30
    properties:
      hbase.regionserver.handler.count: 30
      hbase.regionserver.msginterval: 3000
      hbase.regionserver.optionallogflushinterval: 1000
      hbase.regionserver.regionSplitLimit: 1

  hbase1:
    zookeeper_quorum: "zk1.example.com,zk2.example.com,zk3.example.com"
    zookeeper_port: 2181
    zookeeper_znode_parent: "/hbase"
    hbase_rootdir: "hdfs://hdfs.example.com:8020/hbase"
    hbase_tmp_dir: "/tmp/hbase"
    master_host: "hbase-master1.example.com"
    master_port: 16000
    regionserver_host: "hbase-rs1.example.com"
    regionserver_port: 16020
    timeout: 30
    properties:
      hbase.regionserver.handler.count: 50
      hbase.regionserver.msginterval: 3000
      hbase.regionserver.optionallogflushinterval: 1000
      hbase.regionserver.regionSplitLimit: 1 