# MySQL配置
version: "8.0"
default_instance: "mysql"

# 共享配置
common:
  charset: "utf8mb4"
  collation: "utf8mb4_unicode_ci"
  max_connections: 1000
  timeout: 30

# 多实例配置
instances:
  mysql:
    host: "mysql.example.com"
    port: 3306
    user: "root"
    password: "dev123"
    database: "autoevs_dev"
    properties:
      wait_timeout: 28800
      interactive_timeout: 28800
      max_allowed_packet: 16777216

  mysql1:
    host: "mysql1.example.com"
    port: 3306
    user: "root"
    password: "dev123"
    database: "autoevs_dev1"
    properties:
      wait_timeout: 28800
      interactive_timeout: 28800
      max_allowed_packet: 16777216 