-- YARN管理资源信息表
CREATE TABLE IF NOT EXISTS yarn_management_resources (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    cluster_name VARCHAR(100) NOT NULL COMMENT '集群名称',
    collect_time DATETIME NOT NULL COMMENT '数据采集时间(命令执行时间)',
    insert_time DATETIME NOT NULL COMMENT '数据插入时间(写入数据库时间)',
    total_nodes INT NOT NULL COMMENT '总节点数量',
    active_nodes INT NOT NULL COMMENT '活跃节点数量',
    decommissioned_nodes INT NOT NULL COMMENT '停用节点数量',
    lost_nodes INT NOT NULL COMMENT '丢失节点数量',
    unhealthy_nodes INT NOT NULL COMMENT '不健康节点数量',
    total_memory_mb BIGINT NOT NULL COMMENT '总内存容量(MB)',
    total_vcores INT NOT NULL COMMENT '总虚拟CPU核心数',
    used_memory_mb BIGINT NOT NULL COMMENT '已使用内存(MB)',
    used_vcores INT NOT NULL COMMENT '已使用虚拟CPU核心数',
    available_memory_mb BIGINT NOT NULL COMMENT '可用内存(MB)',
    available_vcores INT NOT NULL COMMENT '可用虚拟CPU核心数',
    memory_utilization_percent DECIMAL(5,2) NOT NULL COMMENT '内存利用率(%)',
    vcore_utilization_percent DECIMAL(5,2) NOT NULL COMMENT 'CPU利用率(%)',
    running_containers INT NOT NULL COMMENT '运行中容器数量',
    INDEX idx_cluster_name (cluster_name) COMMENT '集群名称索引',
    INDEX idx_collect_time (collect_time) COMMENT '采集时间索引',
    INDEX idx_insert_time (insert_time) COMMENT '插入时间索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='YARN管理资源信息表';

-- YARN队列资源配置信息表
CREATE TABLE IF NOT EXISTS yarn_queue_resources (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    cluster_name VARCHAR(100) NOT NULL COMMENT '集群名称',
    queue_name VARCHAR(100) NOT NULL COMMENT '队列名称',
    collect_time DATETIME NOT NULL COMMENT '数据采集时间(命令执行时间)',
    insert_time DATETIME NOT NULL COMMENT '数据插入时间(写入数据库时间)',
    state VARCHAR(50) NOT NULL COMMENT '队列状态',
    capacity_percent DECIMAL(5,2) NOT NULL COMMENT '队列容量百分比',
    maximum_capacity_percent DECIMAL(5,2) NOT NULL COMMENT '最大容量百分比',
    current_capacity_percent DECIMAL(5,2) NOT NULL COMMENT '当前容量百分比',
    num_containers INT NOT NULL COMMENT '容器数量',
    used_memory_mb BIGINT NOT NULL COMMENT '已使用内存(MB)',
    used_vcores INT NOT NULL COMMENT '已使用虚拟CPU核心数',
    reserved_memory_mb BIGINT NOT NULL COMMENT '预留内存(MB)',
    reserved_vcores INT NOT NULL COMMENT '预留虚拟CPU核心数',
    max_memory_mb BIGINT NOT NULL COMMENT '最大内存(MB)',
    max_vcores INT NOT NULL COMMENT '最大虚拟CPU核心数',
    min_memory_mb BIGINT NOT NULL COMMENT '最小内存(MB)',
    min_vcores INT NOT NULL COMMENT '最小虚拟CPU核心数',
    pending_containers INT NOT NULL COMMENT 'Pending容器数量',
    running_containers INT NOT NULL COMMENT '运行中容器数量',
    INDEX idx_cluster_queue (cluster_name, queue_name) COMMENT '集群和队列索引',
    INDEX idx_collect_time (collect_time) COMMENT '采集时间索引',
    INDEX idx_insert_time (insert_time) COMMENT '插入时间索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='YARN队列资源配置信息表';

CREATE TABLE `yarn_application_stats` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `cluster_name` varchar(100) NOT NULL COMMENT '集群名称',
  `collect_time` datetime NOT NULL COMMENT '采集时间',
  `insert_time` datetime NOT NULL COMMENT '插入时间',
  `active_apps` int(11) NOT NULL DEFAULT '0' COMMENT '活跃作业数',
  `completed_apps` int(11) NOT NULL DEFAULT '0' COMMENT '已完成作业数',
  `killed_apps` int(11) NOT NULL DEFAULT '0' COMMENT '被kill的作业数',
  `failed_apps` int(11) NOT NULL DEFAULT '0' COMMENT '失败的作业数',
  `abnormal_apps` int(11) NOT NULL DEFAULT '0' COMMENT '异常作业数',
  `total_submitted_apps` int(11) NOT NULL DEFAULT '0' COMMENT '已提交作业总数',
  PRIMARY KEY (`id`),
  KEY `idx_cluster_collect_time` (`cluster_name`,`collect_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='YARN应用状态统计表';

CREATE TABLE `yarn_application_snapshots` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `cluster_name` varchar(100) NOT NULL COMMENT '集群名称',
  `collect_time` datetime NOT NULL COMMENT '采集时间',
  `insert_time` datetime NOT NULL COMMENT '插入时间',
  `application_id` varchar(100) NOT NULL COMMENT '应用ID',
  `application_name` varchar(255) DEFAULT NULL COMMENT '应用名称',
  `application_type` varchar(50) DEFAULT NULL COMMENT '应用类型',
  `application_tags` text DEFAULT NULL COMMENT '应用标签',
  `user` varchar(100) DEFAULT NULL COMMENT '提交用户',
  `queue` varchar(100) DEFAULT NULL COMMENT '使用队列',
  `state` varchar(20) DEFAULT NULL COMMENT '当前状态',
  `final_status` varchar(20) DEFAULT NULL COMMENT '最终状态',
  `progress` float DEFAULT 0 COMMENT '进度',
  `tracking_url` text DEFAULT NULL COMMENT '跟踪URL',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `finish_time` datetime DEFAULT NULL COMMENT '结束时间',
  `elapsed_time` bigint(20) DEFAULT 0 COMMENT '运行时长(毫秒)',
  `am_container_logs_url` text DEFAULT NULL COMMENT 'AM容器日志URL',
  `allocated_mb` int(11) DEFAULT 0 COMMENT '已分配内存(MB)',
  `allocated_vcores` int(11) DEFAULT 0 COMMENT '已分配CPU核心数',
  `running_containers` int(11) DEFAULT 0 COMMENT '运行容器数',
  `memory_seconds` bigint(20) DEFAULT 0 COMMENT '内存秒数',
  `vcore_seconds` bigint(20) DEFAULT 0 COMMENT 'CPU核心秒数',
  `queue_usage_percentage` float DEFAULT 0 COMMENT '队列资源占用百分比',
  `cluster_usage_percentage` float DEFAULT 0 COMMENT '集群资源占用百分比',
  `preempted_resource_mb` int(11) DEFAULT 0 COMMENT '被抢占的内存(MB)',
  `preempted_resource_vcores` int(11) DEFAULT 0 COMMENT '被抢占的CPU核心数',
  `num_non_am_container_preempted` int(11) DEFAULT 0 COMMENT '被抢占的非AM容器数',
  `num_am_container_preempted` int(11) DEFAULT 0 COMMENT '被抢占的AM容器数',
  `diagnostics` text DEFAULT NULL COMMENT '诊断信息',
  PRIMARY KEY (`id`),
  KEY `idx_cluster_collect_time` (`cluster_name`,`collect_time`),
  KEY `idx_application_id` (`application_id`),
  KEY `idx_user` (`user`),
  KEY `idx_queue` (`queue`),
  KEY `idx_state` (`state`),
  KEY `idx_submit_time` (`submit_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='YARN应用快照信息表'; 